apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumestorage }}
