apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: {{ .Values.volumestorage }}